### ISSUE TITLE
Italic comments

### ISSUE THREAD

**Issue by hrkcz001** [Alexis12119/nightly.nvim#8]
Is it possible to disable italic comments(in old version)?

**Comment by Alexis12119** [comment]
Yeah, maybe I'll add option later because I'm flooded with projects in our school.

**Comment by Alexis12119** [comment]
Hi, I implemented it now check this commit [d24275a](https://github.com/Alexis12119/nightly.nvim/commit/d24275a41d80d5b704cdc296c07ba491fa6d256b). I also tried to improve it. Hope it works. Sorry, that I removed it.

**Comment by hrkcz001** [comment]
> Hi, I implemented it now check this commit [d24275a](https://github.com/Alexis12119/nightly.nvim/commit/d24275a41d80d5b704cdc296c07ba491fa6d256b). I also tried to improve it. Hope it works. Sorry, that I removed it.

Thx, great colorscheme btw!
