### ISSUE TITLE
get nightly colors

### ISSUE THREAD

**Issue by 12-G** [Alexis12119/nightly.nvim#9]
Hi! I am a big fan of your colors and your highlight for the plugins.
I want to know how to get the nightly.nvim colors.
such as: `local colors = require("nightly.palette").dark_colrs` ?

**Comment by Alexis12119** [comment]
```lua
local colors = require("nightly.palette").dark_colors
```

**Comment by Alexis12119** [comment]
As you can see, that's what I used here.

https://github.com/Alexis12119/nightly.nvim/blob/main/lua%2Fnightly%2Ftheme.lua#L6
